# conda env create environment.yml
name: notebooks
channels:
  - ioos
  - conda-forge
dependencies:
  - python=2.7
  #- oceans
  - cartopy
  - folium
  - mpld3
  - numpy
  - pandas
  - pillow
  - scipy
  - vincent
